services:
  llama:
    build: .
    container_name: llama-cpp
    restart: unless-stopped

    ports:
      - "${PORT:-8080}:8080"

    volumes:
      - ./modele:/app/modele

    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - LLAMA_CACHE=/app/modele

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    command: >
      -hf unsloth/Qwen3.6-27B-MTP-GGUF:UD-Q4_K_XL
      -ngl 99 -c 262144 -fa on -np 1
      --spec-type draft-mtp --spec-draft-n-max 2
      --cache-type-k q8_0 --cache-type-v q8_0
      --log-verbose --log-colors on
      --host 0.0.0.0 --port 8080
