services:
  llama:
    build: .
    container_name: llama-cpp
    restart: unless-stopped

    ports:
      - "${PORT:-1234}:8080"

    volumes:
      - ./modele:/app/modele

    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - LLAMA_CACHE=${LLAMA_CACHE:-/app/modele}

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    command: >
      -hf ${HF_REPO}
      -ngl ${GPU_LAYERS:-99}
      -c ${CTX_SIZE:-262144}
      -t ${THREADS:-6}
      -b ${BATCH_SIZE:-512}
      -fa on
      -np ${PARALLEL:-1}
      --tensor-split ${TENSOR_SPLIT:-0.75,0.25}
      --cache-type-k q4_0
      --cache-type-v q4_0
      --spec-type draft-mtp --spec-draft-n-max 2
      --log-verbose --log-colors on
      --host 0.0.0.0 --port 8080
